<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Thread extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'description' => $this->description,
            'created_at' => $this->created_at,
            'author' => $this->user->username,
            'topics' => route('thread.topics', ['id' => $this->id])
        ];
    }

    public function with($request)
    {
        return [
            'version' => '1.0.0',
            'author' => 'J.J. Strootman'
        ];
    }

    public function withResponse($request, $response)
    {
        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }
}
